version: "3.0"

services:
  polkadot:
    image: parity/polkadot
    container_name: polkadot
    ports:
      - "9944:9944"
      - "9615:9615"
    restart: always
    volumes:
      - ./data:/polkadot
